"""
AgentLink Async & Streaming Example.

Demonstrates:
- Async agent handlers (async def)
- Streaming message responses
- Async bus operations

Inspired by: Agent Lightning streaming patterns and VibeVoice async design.

Usage:
    python 05_async_streaming.py
"""

import asyncio
import time
from agentlink import AgentNode, AgentBus, AgentMessage
from agentlink.protocol.message import MessageType


# ─── Async Agent Handlers ────────────────────────────────────────────────────

async def async_researcher(message: AgentMessage) -> str:
    """
    Async researcher agent that processes requests with simulated delay.
    In production, this would call an LLM API.
    """
    query = message.content
    await asyncio.sleep(0.5)  # Simulate LLM processing
    
    findings = {
        "AI trends": "Multi-agent systems, MCP protocol, and local LLMs are trending in 2026.",
        "default": f"Research findings for: {query}",
    }
    return findings.get(query, findings["default"])


async def async_writer(message: AgentMessage) -> str:
    """Async writer agent that formats research into articles."""
    content = message.content
    await asyncio.sleep(0.3)  # Simulate writing
    
    return f"""# Research Report

{content}

*Generated by AgentLink async writer at {time.strftime('%Y-%m-%d %H:%M:%S')}*
"""


async def streaming_analyst(message: AgentMessage) -> str:
    """
    Analyst agent that supports chunked streaming responses.
    Yields partial results for real-time display.
    """
    query = message.content
    chunks = [
        f"Analyzing: '{query}'...\n",
        f"Step 1: Collecting data points\n",
        f"Step 2: Evaluating patterns\n",
        f"Step 3: Computing relevance scores\n",
        f"Conclusion: {query} requires multi-dimensional analysis.\n",
    ]
    
    result = ""
    for chunk in chunks:
        await asyncio.sleep(0.2)
        result += chunk
        # In a real streaming scenario, you would yield here:
        # yield chunk
    
    return result


# ─── Streaming Message Bus ───────────────────────────────────────────────────

class AsyncAgentBus(AgentBus):
    """
    Async-aware AgentBus that supports:
    - await bus.send_async()
    - Streaming message responses
    - Concurrent agent execution
    """
    
    async def send_async(self, sender: str, recipient: str, content: str) -> AgentMessage:
        """
        Async version of bus-level send.
        
        Returns the reply message after agent processes.
        """
        # Look up recipient node
        recipient_node = None
        for node_id, node in self._nodes.items():
            if node_id == recipient:
                recipient_node = node
                break
        
        if not recipient_node:
            raise ValueError(f"Unknown agent: {recipient}")
        
        # Create request message
        msg = AgentMessage(
            type=MessageType.REQUEST,
            sender=self._parse_address(sender),
            recipient=self._parse_address(recipient),
            content=content,
        )
        
        # Call async handler
        handler = getattr(recipient_node, "_handler", None)
        if handler is None:
            raise RuntimeError(f"Agent {recipient} has no handler")
        
        # Handle both sync and async handlers
        if asyncio.iscoroutinefunction(handler):
            result = await handler(msg)
        else:
            result = handler(msg)
        
        # Create reply
        reply = msg.reply(result)
        return reply
    
    def _parse_address(self, addr: str):
        """Parse address string to AgentAddress."""
        from agentlink.protocol.message import AgentAddress
        if "@" in addr:
            parts = addr.split("@")
            return AgentAddress(parts[0], parts[1] if len(parts) > 1 else "default")
        return AgentAddress(addr, "default")


# ─── Demo ────────────────────────────────────────────────────────────────────

async def demo_async_handlers():
    """Demo: Direct async agent handlers."""
    print("=" * 60)
    print("Demo 1: Async Agent Handlers")
    print("=" * 60)
    
    researcher = AgentNode("researcher", async_researcher, capabilities=["research"])
    writer = AgentNode("writer", async_writer, capabilities=["writing"])
    analyst = AgentNode("analyst", streaming_analyst, capabilities=["analysis"])
    
    bus = AsyncAgentBus(name="async-demo")
    bus.register_many(researcher, writer, analyst)
    
    # Time concurrent agent executions
    start = time.time()
    
    # Fire multiple agents concurrently
    results = await asyncio.gather(
        researcher.send("writer", "AI trends"),
        analyst.send("writer", "market data"),
    )
    
    elapsed = time.time() - start
    print(f"\nConcurrent execution completed in {elapsed:.2f}s")
    
    for reply in results:
        print(f"\n[From: {reply.sender.agent_id}]")
        print(reply.content[:80] + "..." if len(reply.content) > 80 else reply.content)
    
    return results


async def demo_streaming():
    """Demo: Streaming responses with chunked output."""
    print("\n" + "=" * 60)
    print("Demo 2: Streaming Analysis")
    print("=" * 60)
    
    analyst = AgentNode("analyst", streaming_analyst, capabilities=["analysis"])
    
    msg = AgentMessage(
        type=MessageType.REQUEST,
        sender=AgentAddress("client", "demo"),
        recipient=AgentAddress("analyst", "demo"),
        content="user engagement metrics",
    )
    
    print("\nStreaming output:")
    print("-" * 40)
    
    # Simulate streaming display
    result = await analyst.send("analyst", "user engagement metrics")
    
    print("\n" + "-" * 40)
    print(f"Complete response ({len(result.content)} chars):")
    print(result.content)


async def demo_async_bus():
    """Demo: Async bus operations."""
    print("\n" + "=" * 60)
    print("Demo 3: Async AgentBus Operations")
    print("=" * 60)
    
    bus = AsyncAgentBus(name="production")
    bus.register_many(
        AgentNode("planner", async_researcher, capabilities=["planning"]),
        AgentNode("executor", async_writer, capabilities=["execution"]),
    )
    
    start = time.time()
    
    # Async send through bus
    reply = await bus.send_async("planner", "executor", "Q1 financial report")
    
    elapsed = time.time() - start
    print(f"\nAsync bus send completed in {elapsed:.2f}s")
    print(f"Reply: {reply.content[:100]}...")


async def main():
    """Run all async demos."""
    print("AgentLink Async & Streaming Demo")
    print("=" * 60)
    
    await demo_async_handlers()
    await demo_streaming()
    await demo_async_bus()
    
    print("\n" + "=" * 60)
    print("All demos completed!")
    print("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
